account/urls.py
from django.urls import path
from . import views
app_name='account'
urlpatterns = [
    path('login', views.getLogin.as_view(), name="login"),
    path('register', views.getRegister.as_view(), name="register"),
    path('changepass', views.PasswordChange.as_view(), name="change_password"),
    path('logout', views.getLogout.as_view(), name="logout"),
    path('activate/<uidb>/<token>',views.activate, name='activate'),
    path('profile',views.getProfile.as_view(), name='profile'),
    path('profile/create', views.CustomerAccount.as_view(), name='account'),
    path('shipping/create', views.CustomerShipping.as_view(), name='create_shipping'),
    path('shipping/update', views.UpdateShipping.as_view(), name='update_shipping'),

]

customizeSite/urls.py
from django.urls import path
from .views import GetContact

app_name='customizeSite'
urlpatterns = [
    path('contact', GetContact.as_view(), name="contact")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("product.urls", namespace="product")),
    path('', include("account.urls", namespace="account")),
    path('', include("customizeSite.urls", namespace="site")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = "ecommerce"
urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('shop', views.GetShop.as_view(), name="shop"),
    path('product/<int:id>', views.getSingleProduct.as_view(), name="single"),
    path('cart', views.getCart.as_view(), name="cart"),
    path('checkout', views.Checkout.as_view(), name="checkout"),
]

templates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
    <head>
    <title>Elite Shoppy an Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
    <!--/tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Elite Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
            function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--//tags -->
        {% load staticfiles %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>
    <!-- //for bootstrap working -->
    <style>
        ul.dropdown-menu li a {
            color: black;
        }
        ul.dropdown-menu li {
        display: block;
        width: 100%;
        text-align: left;
        padding: 7px 0;
        letter-spacing: 1px;
        border-right: none;
    }
        .open > .dropdown-menu {
        display: block;
        margin-left: 73px;
    }
        a.w3view-cart {
        outline: none;
        border: none;
        background: #17c3a2;
        width: 48px;
        height: 43px;
        font-size: 50px;
        color: #000;
        padding: 4px 55px;
    }
        a#dropdownMenu1 {
        cursor: pointer;
    }
    </style>
    {% block stylesheet %}

    {% endblock %}
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    </head>
<body>
<!-- header -->
<div class="header" id="home">
	<div class="container">
		<ul>
		    {% if request.user.is_authenticated %}
            <li>
                <div class="dropdown">
                  <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="fa fa-user-circle-o"></i>{{ request.user.get_full_name }}
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="{% url 'account:profile' %}"><i class="fa fa-user-circle"></i>Profile</a></li>
                    <li><a href="#"><i class="fa fa-cog"></i>Settings</a></li>
                    <li><a href="{% url 'account:change_password' %}"><i class="fa fa-lock"></i> Change password</a></li>
                    <li><a href="{% url 'product:cart' %}"><i class="fa fa-shopping-cart"></i>Cart</a></li>
                    <li> <a href="{% url 'account:logout' %}"><i class="fa fa-power-off"></i>Logout</a></li>
                  </ul>
                </div>
            </li>
                {% if request.user.is_superuser %}
            <li> <a href="/admin"><i class="fa fa-tachometer"></i>Admin</a></li>
                {% endif %}
            {% else %}
            <li> <a href="{% url 'account:login' %}"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Sign In </a></li>
            <li> <a href="{% url 'account:register' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Sign Up </a></li>
		    {% endif %}
			<li><i class="fa fa-phone" aria-hidden="true"></i> Call : 01234567898</li>
			<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com">info@example.com</a></li>
		</ul>
	</div>
</div>
<!-- //header -->
<!-- header-bot -->
<div class="header-bot">
	<div class="header-bot_inner_wthreeinfo_header_mid">
		<div class="col-md-4 header-middle">
			<form action="{% url 'product:shop' %}" method="get">
                <input type="search" name="s" value="{{ request.GET.s }}" placeholder="Search here..." required="">
                <input type="submit" value=" ">
                <div class="clearfix"></div>
			</form>
		</div>
		<!-- header-bot -->
        <div class="col-md-4 logo_agile">
            <h1><a href="{% url 'product:index' %}"><span>D</span>jango Shop <i class="fa fa-shopping-bag top_logo_agile_bag" aria-hidden="true"></i></a></h1>
        </div>
        <!-- header-bot -->
		<div class="col-md-4 agileits-social top_content">
            <ul class="social-nav model-3d-0 footer-social w3_agile_social">
                <li class="share">Share On : </li>
                <li><a href="#" class="facebook">
                      <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="twitter">
                      <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="instagram">
                      <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="pinterest">
                      <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
            </ul>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- //header-bot -->
<!-- banner -->
<div class="ban-top">
	<div class="container">
		<div class="top_nav_left">
            {% block nav %}
            {% endblock %}
        </div>
		<div class="top_nav_right">
			<a href="{% url 'product:cart' %}" class="w3view-cart"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- //banner-top -->
{% block content %}

{% endblock %}

<!-- footer -->
<div class="footer">
	<div class="footer_agile_inner_info_w3l">
		<div class="col-md-3 footer-left">
			<h2><a href="index.html"><span>D</span>jango Shop </a></h2>
			<p>Lorem ipsum quia dolorsit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora.</p>
			<ul class="social-nav model-3d-0 footer-social w3_agile_social two">
                <li><a href="#" class="facebook">
                      <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="twitter">
                      <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="instagram">
                      <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
                <li><a href="#" class="pinterest">
                      <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                      <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
            </ul>
		</div>
		<div class="col-md-9 footer-right">
			<div class="sign-grds">
				<div class="col-md-4 sign-gd">
					<h4>Our <span>Information</span> </h4>
					<ul>
						<li><a href="{% url 'product:index' %}">Home</a></li>
						<li><a href="{% url 'product:shop' %}?cat=men">Men's Wear</a></li>
						<li><a href="{% url 'product:shop' %}?cat=women">Women's wear</a></li>

						<li><a href="{% url 'site:contact' %}">Contact</a></li>
					</ul>
				</div>

				<div class="col-md-5 sign-gd-two">
					<h4>Store <span>Information</span></h4>
					<div class="w3-address">
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-phone" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Phone Number</h6>
								<p>+8801763433486</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Email Address</h6>
								<p>Email :<a href="mailto:nasiruiucse@gmail.com">nasiruiucse@gmail.com</a></p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-address-grid">
							<div class="w3-address-left">
								<i class="fa fa-map-marker" aria-hidden="true"></i>
							</div>
							<div class="w3-address-right">
								<h6>Location</h6>
								<p>Natun bazar, Badda, Dhaka, Bangladesh
								</p>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
				<div class="col-md-3 sign-gd flickr-post">
					<h4>Flickr <span>Posts</span></h4>
					<ul>
						<li><a href="single.html"><img src="{% static 'images/t1.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t2.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t3.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t4.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t1.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t2.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t3.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t2.jpg' %}" alt=" " class="img-responsive" /></a></li>
						<li><a href="single.html"><img src="{% static 'images/t4.jpg' %}" alt=" " class="img-responsive" /></a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="clearfix"></div>
			<div class="agile_newsletter_footer">
					<div class="col-sm-6 newsleft">
				<h3>SIGN UP FOR NEWSLETTER !</h3>
			</div>
			<div class="col-sm-6 newsright">
				<form action="#" method="post">
					<input type="email" placeholder="Enter your email..." name="email" required="">
					<input type="submit" value="Submit">
				</form>
			</div>

		<div class="clearfix"></div>
	</div>
		<p class="copy-right">&copy; 2018 Django Shop. All rights reserved | Developed by <a href="https://www.facebook.com/404detector">Nasir</a></p>
	</div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<!-- Custom-JavaScript-File-Links -->
<!-- cart-js -->
<script src="{% static 'js/minicart.min.js' %}"></script>
<script>
	// Mini Cart
	paypal.minicart.render({
		action: '#'
	});

	if (~window.location.search.indexOf('reset=true')) {
		paypal.minicart.reset();
	}
</script>

<!-- //cart-js -->
<!-- script for responsive tabs -->
<script src="{% static 'js/easy-responsive-tabs.js' %}"></script>
<script>
	$(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true,   // 100% fit in a container
            closed: 'accordion', // Start closed if in accordion view
            activate: function(event) { // Callback function if tab is switched
                var $tab = $(this);
                var $info = $('#tabInfo');
                var $name = $('span', $info);
                $name.text($tab.text());
                $info.show();
        }
    });
    $('#verticalTab').easyResponsiveTabs({
        type: 'vertical',
        width: 'auto',
        fit: true
    });
	});
</script>
<!-- //script for responsive tabs -->
<!-- stats -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.countup.js' %}"></script>
<script>
    $('.counter').countUp();
</script>
<!-- //stats -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing.min.js' %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function() {

    $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->


<!-- for bootstrap working -->
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
{% block script %}
    
{% endblock %}
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% block stylesheet %}

{% endblock %}
{% block nav %}
{% include 'nav.html' %}
{% endblock %}
{% block content %}
    <div class="page-head_agile_info_w3l">
		<div class="container">
			<h3>C<span>heck Out </span></h3>
            <div class="services-breadcrumb">
                <div class="agile_inner_breadcrumb">
                   <ul class="w3_short">
                       <li><a href="{% url 'product:index' %}">Home</a><i>|</i></li>
                       <li><a href="{% url 'ecommerce:cart' %}">Cart</a><i>|</i></li>
                       <li>Check out</li>
                   </ul>
                </div>
            </div>
	    </div>
    </div>
<div class="container">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Check out</h3>
      </div>
      <div class="panel-body">
        <h3>Billing Details</h3>
        <form action="" method="POST" style="margin-top: 20px;">
        {% csrf_token %}
          <div class="row">
              <div class="col-md-6">
                  <div class="form-group">
                    <label for="firstname">First Name:</label>
                    <input type="text" class="form-control" value="{{ customer.name.first_name }}" id="firstname" placeholder="First name">
                  </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group">
                    <label for="lastname">Last Name:</label>
                    <input type="text" class="form-control" value="{{ customer.name.last_name }}" id="lastname" placeholder="Last name">
                  </div>
              </div>

          </div>
            <div class="row">
              <div class="col-md-12">
                  <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" value="{{ customer.name.email }}" id="email" placeholder="Email">
                  </div>
              </div>
          </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="city">City:</label>
                        <input type="text" class="form-control" value="{{ shipping.city }}" id="city" placeholder="City">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="area">Area:</label>
                <input type="text" class="form-control" value="{{ shipping.area }}" id="area" placeholder="Area">
            </div>

            <div class="form-group">
                <label for="address">Address:</label>
                <textarea class="form-control" id="address" rows="10" placeholder="address">{{ shipping.address }}</textarea>
            </div>

            <div class="form-group">
                <label for="contact">Contact:</label>
                <input type="tel" class="form-control" id="contact" value="{{ shipping.alternative_mobile_no }}" placeholder="Contact">
            </div>


            <h3>Your Order:</h3>
            <div class="row">
                <div class="col-md-8">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th>Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for c in cart %}
                            <tr>
                            <td>{{ c.products.name }}*{{ c.quantity }}</td>
                            <td>{{ c.products.sale_price }}*{{ c.quantity }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-4"></div>
            </div>
          <button type="submit" class="btn btn-default">Place order</button>
        </form>
      </div>
    </div>
</div>
{% endblock %}
{% block script %}

{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block stylesheet %}
    <style>
    .panel-body form p {
    padding: 15px;
}
    button.btn.btn-primary {
    margin-left: 15px;
}
    </style>
{% endblock %}
{% block nav %}
{% include 'nav.html' %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
          </div>
          <div class="panel-body">
              <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary">{{ btn }}</button>
              </form>
          </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
    $(document).ready(function(){
        $(".panel-body p input").addClass('form-control');
        $(".panel-body p textarea").addClass('form-control');
    });
    </script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block stylesheet %}

{% endblock %}
{% block nav %}
{% include 'nav.html' %}
{% endblock %}
{% block content %}
    {% load staticfiles %}
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
						<div class="modal-body modal-body-sub_agile">
						<div class="col-md-8 modal_body_left modal_body_left1">
						<h3 class="agileinfo_sign">Sign In <span>Now</span></h3>
									<form action="" method="post">
                                        {% csrf_token %}
							<div class="styled-input agile-styled-input-top">
								<input type="text" name="username" required="">
								<label>Username</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="password" name="password" required="">
								<label>Password</label>
								<span></span>
							</div>
							<input type="submit" value="Sign In">
						</form>
						  <ul class="social-nav model-3d-0 footer-social w3_agile_social top_agile_third">
															<li><a href="#" class="facebook">
																  <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="twitter">
																  <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="instagram">
																  <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="pinterest">
																  <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
														</ul>
														<div class="clearfix"></div>
														<p><a href="{% url 'account:register' %}"> Don't have an account?</a></p>

						</div>
						<div class="col-md-4 modal_body_right modal_body_right1">
							<img src="{% static 'images/log_pic.jpg' %}" alt=" "/>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<!-- //Modal content-->
			</div>
{% endblock %}
{% block script %}

{% endblock %}

templates/nav.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav menu__list">
        <li class="active menu__item menu__item--current"><a class="menu__link" href="{% url 'product:index' %}">Home <span class="sr-only">(current)</span></a></li>
        <li class=" menu__item"><a class="menu__link" href="{% url 'product:shop' %}">Shop</a></li>
        {% for cat in category %}
            <li class="dropdown menu__item">
            <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ cat.name }} <span class="caret"></span></a>
                <ul class="dropdown-menu multi-column columns-3">
                    <div class="agile_inner_drop_nav_info">
                        <div class="col-sm-6 multi-gd-img1 multi-gd-text ">
                            <a href="{% url 'product:shop' %}?cat={{ cat.name }}"><img src="{{ cat.image.url }}" alt=" "/></a>
                        </div>
                        <div class="col-sm-3 multi-gd-img">
                            <ul class="multi-column-dropdown">
                                {% for s in subcategory %}
                                    {% if s.category.id == cat.id %}
                                        <li><a href="{% url 'product:shop' %}?cat={{ cat.name }}&sub={{ s.name }}">{{ s.name }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </ul>
        </li>
        {% endfor %}
        <li class=" menu__item"><a class="menu__link" href="{% url 'site:contact' %}">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>

templates/register.html
{% extends 'base.html' %}
{% block stylesheet %}

{% endblock %}
{% block nav %}
{% include 'nav.html' %}
{% endblock %}
{% block content %}
{% load staticfiles %}
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
						<div class="modal-body modal-body-sub_agile">
						<div class="col-md-8 modal_body_left modal_body_left1">
						<h3 class="agileinfo_sign">Sign Up <span>Now</span></h3>
						 <form action="#" method="post">
                             {% csrf_token %}
							<div class="styled-input agile-styled-input-top">
								<input type="text" name="first_name" required="">
								<label>First name</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="text" name="last_name" required="">
								<label>Last name</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="text" name="username" required="">
								<label>Username</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="email" name="email" required="">
								<label>Email</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="password" name="password1" required="">
								<label>Password</label>
								<span></span>
							</div>
							<div class="styled-input">
								<input type="password" name="password2" required="">
								<label>Confirm Password</label>
								<span></span>
							</div>
							<input type="submit" value="Sign Up">
						</form>
						  <ul class="social-nav model-3d-0 footer-social w3_agile_social top_agile_third">
															<li><a href="#" class="facebook">
																  <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="twitter">
																  <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="instagram">
																  <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
															<li><a href="#" class="pinterest">
																  <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
																  <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
														</ul>
														<div class="clearfix"></div>
														<p><a href="#">By clicking register, I agree to your terms</a></p>

						</div>
						<div class="col-md-4 modal_body_right modal_body_right1">
							<img src="{% static 'images/log_pic.jpg' %}" alt=" "/>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<!-- //Modal content-->
			</div>
{% endblock %}
{% block script %}

{% endblock %}

templates/sample.html
{% extends 'base.html' %}
{% block stylesheet %}

{% endblock %}
{% block nav %}
{% include 'nav.html' %}
{% endblock %}
{% block content %}

{% endblock %}
{% block script %}

{% endblock %}